/**
 * {{%project name%}}
 * Generated by Gensokyo Generator
 */
module.exports = {
    host        : "127.0.0.1",
    port        : 3721,
    "class"     : "{{%project name lowercase%}}",
    "defaultId" : "{{%project name lowercase%}}",

    logPath     : undefined,
    logLevel    : "ALL"
};
