/**
 * {{%project name%}}
 * Generated by Gensokyo Generator
 */
var _require = function(name) {
    try {
        return require("./" + name);
    } catch(e) {
        try {
            return require("./" + name + ".sample");
        } catch(e) {
            return {};
        }
    }
};

module.exports = {
    server          : _require("server"),
    zookeeper       : _require("zookeeper"),
    metrics         : _require("metrics")
};

