/**
 * {{%project name%}}
 * Generated by Gensokyo Generator
 */
var config = require("./config");
var options = {
    host        : config.server.host,
    port        : config.server.port,

    "class"     : config.server.class,
    id          : config.server.defaultId,

    zookeeper   : config.zookeeper,

    logPath     : config.server.logPath,
    logLevel    : config.server.logLevel
};

var opts = require("nomnom").option("id", {
    abbr    : "i",
    helper  : "server id."
}).parse();

if(opts.id) {
    options.id = opts.id;
}

var gensokyo = require("gensokyo").createServer(options);
gensokyo.start();
